### ISSUE TITLE
Feedback milestone 2

### ISSUE THREAD

**Issue by SuzanaMomo** [data301-2021-summer2/project-group18-project#1]
Hello,

My name is Suzana__ and I will be giving you some feedback on your project.

Overall, the project is a good starting point, but there is some work that needs to be done to elevate this project to our standards so its meets our expectations. 

I have divided up the feedback into several sections so it is easier for you to implement.

## Task 1
Good job!
## Task 2
Good Job!

## Task 3
- [x] Your plots need to be more clear, i.e with proper legends. For instance scatter plots didn't have proper legends. Also, make your plots a bit more fancy.  Follow "principles of effective visualizations" discussed in the class.
- [x] Anikait, please attach the outputs also in your notebook i.e show your plots as well like your other team members have, otherwise it is difficult for me to check. 

## Task 4

- [x]  Along with the existing plots try have another type of plots that will help visualize your research questions more
